package pe.com.hiper.bmatic.perfilagendamientows.web.errors;


import org.springframework.http.HttpStatus;

public class InvalidRequestException extends ControllerException {

    /**
     * InvalidRequestException
     */
    private static final long serialVersionUID = 1L;
    private static final String TEMPLATE = "Error '%s' generated by invalid request";

    public InvalidRequestException(String exception) {
        super(HttpStatus.BAD_REQUEST, String.format(TEMPLATE, exception));
    }
}
